### ISSUE TITLE
Other ways to trigger `route()`

### ISSUE THREAD

**Issue by DarrenSem** [mitchwadair/vanilla-spa-router#4]
Hey, just watched your video, nice and short but good content. Helped reinforce what I have been learning today about client-side routing in modern ES6.

Right now this example jumps between routes only via normal-looking `<a href>`tags that call an overriding `route(thisEvent)` function.

What about if we want to call that `route` function directly instead of only during a triggered event... maybe add a new example .html page (that get fetched) that demonstrates this (I guess `route` would no longer presume an event arg etc.)

**Comment by mitchwadair** [comment]
Hi! I appreciate the comment and request. I want to keep this repo basically the same for the sake of keeping it in-line with the video, but to answer your question regarding calling `route` directly, it would not be particularly difficult.

The key thing to know is that in order for anything to really happen on a page, there must be an event. While the `route` function does not need to be the event handler, it would likely be called by an event handler. Let's say you wanted a `button` to call `route`. Your HTML may look like this:
```html
<button id="my-button">
    Click me!
</button>
```
And you'd need a handler for this button when it gets clicked. This can be done either like in the current example with an anchor tag where you inline the call on the element, or you can create an event handler that targets the button itself in JS:
```js
document.getElementById("my-button").addEventListener("click", () => {
    // perform some action
});
```
Now, with this setup we'd want to change how we write the `route` function. Currently we rely on the `event` passed to `route` in order to get the location we want to navigate to. In this case, we don't want to rely on that. Lets say we know we want `my-button` to navigate the user to `/my-new-page`. We can now rewrite `route` as:
```js
// destination is a string
const route = (destination) => {
    window.history.pushState({}, "", destination);
    handleLocation();
};
```
Now that we have this, we can update our event listener on the button:
```js
document.getElementById("my-button").addEventListener("click", () => {
    route("/my-new-page");
});
```
With `route` changed to this implementation we'll need a different handler for our anchor tags. That handles the event-related data that `route` previously did, then calls the new `route` function.

All of that said, adding navigation to something like a `button` is a bit of an accessibility no-no, so we'd want to avoid it if possible. If you want the link you click to look like a button, that can easily be done with some CSS.

Hopefully that helps!

**Comment by DarrenSem** [comment]
What about `route(destinationStringorEvent)`

**Comment by mitchwadair** [comment]
Sure, that is also a possibility. In that case, we'd want to do some conditional logic based on the type of the `destinationStringOrEvent` argument.
```js
const route = (destinationStringOrEvent) => {
    let to;
    if (typeof destinationStringOrEvent === "string") {
        to = destinationStringOrEvent;
    } else {
        destinationStringOrEvent = destinationStringOrEvent || window.event;
        destinationStringOrEvent.preventDefault();
        to = destinationStringOrEvent.target.href;
    }
    window.history.pushState({}, "", to);
    handleLocation();
};
```
What we now have is a function that checks the type of the argument. If it is of type `string`, we can assume it is a destination. Otherwise, we can assume it is an event object. We handle assigning the our destination to the `to` variable based on that.

With this, we can leave the anchor tags as-is and also handle the new use-case (the button in my previous example) the same way
